//! One native encoder worker, bounded memory-only cache, validated compatible assets.
use serde::Deserialize;
use sha2::{Digest, Sha256};
use std::collections::VecDeque;
use std::sync::{Arc, LazyLock, Mutex, OnceLock, TryLockError};
use std::time::{Duration, Instant};

#[derive(Deserialize)]
struct Manifest {
    format_version: u32,
    dimension: usize,
    vectors_per_site: usize,
    byte_order: String,
    normalization: String,
    row_ids: Vec<String>,
    model_sha256: String,
    tokenizer_sha256: String,
    engine_revision: String,
    catalog_sha256: String,
    concepts_sha256: String,
    vectors_sha256: String,
    template_version: u32,
}
struct State {
    encoder: search_encoder::Encoder,
    vectors: Vec<(String, Vec<f32>, Vec<f32>)>,
    cache: Mutex<VecDeque<(String, Instant, Arc<Vec<f32>>)>>,
}
struct SearchService {
    state: OnceLock<Result<State, String>>,
    worker: Mutex<()>,
}
static SERVICE: SearchService = SearchService::new();
fn hash(bytes: &[u8]) -> String {
    format!("{:x}", Sha256::digest(bytes))
}
impl State {
    fn new() -> Result<Self, String> {
        let vectors = validate_vectors(
            include_str!("../../assets/search/manifest.json"),
            include_bytes!("../../assets/search/catalog-vectors.bin"),
        )?;
        Ok(Self {
            encoder: search_encoder::Encoder::new().map_err(|e| e.to_string())?,
            vectors,
            cache: Mutex::new(VecDeque::new()),
        })
    }
    fn cached(&self, query: &str) -> Result<Option<Arc<Vec<f32>>>, ()> {
        let mut cache = self.cache.lock().map_err(|_| ())?;
        let Some(index) = cache
            .iter()
            .position(|(q, t, _)| q == query && t.elapsed() < Duration::from_secs(300))
        else {
            return Ok(None);
        };
        let entry = cache.remove(index).unwrap();
        let vector = Arc::clone(&entry.2);
        cache.push_back(entry);
        Ok(Some(vector))
    }
    fn remember(&self, query: &str, vector: Arc<Vec<f32>>) -> Result<(), ()> {
        let mut cache = self.cache.lock().map_err(|_| ())?;
        if cache.len() >= 64 {
            cache.pop_front();
        }
        cache.push_back((query.into(), Instant::now(), vector));
        Ok(())
    }
    fn score(&self, vector: &[f32]) -> (String, Vec<(String, f32)>) {
        // All dot products run against immutable data outside both mutexes.
        let dot = |other: &[f32]| -> f32 { other.iter().zip(vector).map(|(a, b)| a * b).sum() };
        (
            "used".into(),
            self.vectors
                .iter()
                .map(|(id, a, b)| (id.clone(), dot(a).max(dot(b))))
                .collect(),
        )
    }
}
fn validate_vectors(
    manifest: &str,
    bytes: &[u8],
) -> Result<Vec<(String, Vec<f32>, Vec<f32>)>, String> {
    let m: Manifest = serde_json::from_str(manifest).map_err(|e| e.to_string())?;
    if m.format_version != 1
        || m.dimension != 384
        || m.vectors_per_site != 2
        || m.byte_order != "little"
        || m.normalization != "l2"
        || m.template_version != 1
        || hash(include_bytes!("../../assets/search/catalog.json")) != m.catalog_sha256
        || hash(include_bytes!("../../assets/search/concepts.json")) != m.concepts_sha256
        || hash(bytes) != m.vectors_sha256
    {
        return Err("incompatible catalog assets".into());
    }
    // Reject same-dimensional vectors generated by another encoder or pipeline.
    if m.model_sha256 != search_encoder::MODEL_SHA256
        || m.tokenizer_sha256 != search_encoder::TOKENIZER_SHA256
        || m.engine_revision != search_encoder::ENGINE_REVISION
    {
        return Err("missing encoder fingerprint".into());
    }
    let mut expected_ids: Vec<_> = super::catalog().iter().map(|e| e.id.clone()).collect();
    expected_ids.sort();
    if m.row_ids != expected_ids {
        return Err("catalog row mapping mismatch".into());
    }
    if bytes.len() != m.row_ids.len() * 2 * m.dimension * 4 {
        return Err("invalid vector byte length".into());
    }
    let mut floats = Vec::new();
    for chunk in bytes.chunks_exact(4) {
        let value = f32::from_le_bytes(chunk.try_into().unwrap());
        if !value.is_finite() {
            return Err("nonfinite catalog vector".into());
        }
        floats.push(value);
    }
    for vector in floats.chunks_exact(m.dimension) {
        let norm: f32 = vector.iter().map(|v| v * v).sum();
        if (norm - 1.).abs() > 0.01 {
            return Err("unnormalized catalog vector".into());
        }
    }
    let mut vectors = Vec::new();
    for (id, row) in m
        .row_ids
        .into_iter()
        .zip(floats.chunks_exact(m.dimension * 2))
    {
        vectors.push((id, row[..m.dimension].to_vec(), row[m.dimension..].to_vec()));
    }
    Ok(vectors)
}
impl SearchService {
    const fn new() -> Self {
        Self {
            state: OnceLock::new(),
            worker: Mutex::new(()),
        }
    }
    fn scores(&self, query: &str) -> (String, Vec<(String, f32)>) {
        if !concepts_available() {
            return ("unavailable".into(), Vec::new());
        }
        if let Some(state) = self.state.get() {
            let state = match state {
                Ok(state) => state,
                Err(_) => return ("unavailable".into(), Vec::new()),
            };
            match state.cached(query) {
                Ok(Some(vector)) => return state.score(&vector),
                Ok(None) => {}
                Err(()) => return ("unavailable".into(), Vec::new()),
            }
        }
        // Only uncached embeddings compete for the single worker. A second
        // lookup handles a cache publication racing with this initial miss.
        let worker = match self.worker.try_lock() {
            Ok(worker) => worker,
            Err(TryLockError::WouldBlock) => {
                if let Some(Ok(state)) = self.state.get() {
                    match state.cached(query) {
                        Ok(Some(vector)) => return state.score(&vector),
                        Err(()) => return ("unavailable".into(), Vec::new()),
                        Ok(None) => {}
                    }
                }
                return ("busy".into(), Vec::new());
            }
            Err(_) => return ("unavailable".into(), Vec::new()),
        };
        let state = match self.state.get_or_init(State::new) {
            Ok(state) => state,
            Err(_) => return ("unavailable".into(), Vec::new()),
        };
        match state.cached(query) {
            Ok(Some(vector)) => {
                drop(worker);
                return state.score(&vector);
            }
            Ok(None) => {}
            Err(()) => return ("unavailable".into(), Vec::new()),
        }
        let vector = match state
            .encoder
            .embed(&search_encoder::expand_semantic_text(query))
        {
            Ok(vector) if vector.len() == 384 && vector.iter().all(|v| v.is_finite()) => {
                Arc::new(vector)
            }
            _ => return ("unavailable".into(), Vec::new()),
        };
        if state.remember(query, Arc::clone(&vector)).is_err() {
            return ("unavailable".into(), Vec::new());
        }
        drop(worker);
        state.score(&vector)
    }
}
pub(super) fn scores(query: &str) -> (String, Vec<(String, f32)>) {
    SERVICE.scores(query)
}

#[derive(Deserialize)]
struct Concepts {
    concepts: Vec<Concept>,
}
#[derive(Deserialize)]
struct Concept {
    terms: Vec<String>,
    #[serde(rename = "expansion")]
    _expansion: String,
}
static CONCEPTS: LazyLock<Option<Concepts>> =
    LazyLock::new(|| serde_json::from_str(include_str!("../../assets/search/concepts.json")).ok());
pub(super) fn concepts_available() -> bool {
    CONCEPTS.is_some()
}
pub(super) fn expansions(query: &str) -> Vec<String> {
    // Validate the typed asset before using the encoder's shared detector; this
    // preserves lexical fallback if malformed embedded concepts are supplied.
    if concepts_available() {
        search_encoder::semantic_concepts(query)
    } else {
        Vec::new()
    }
}
pub(super) fn max_phrase_words() -> usize {
    CONCEPTS
        .iter()
        .flat_map(|c| c.concepts.iter())
        .flat_map(|c| c.terms.iter())
        .map(|t| t.split_whitespace().count())
        .max()
        .unwrap_or(1)
}
pub(super) fn exact_multiword_concept(query: &str) -> bool {
    let query = super::normalize(super::trim_sentence_punctuation(query));
    CONCEPTS
        .iter()
        .flat_map(|c| c.concepts.iter())
        .flat_map(|c| c.terms.iter())
        .any(|t| t.split_whitespace().count() > 1 && super::normalize(t) == query)
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn concurrent_hot_queries_do_not_compete_for_encoder_worker() {
        use std::sync::{Barrier, mpsc};
        let service = SearchService::new();
        let query = "cached vector synchronization";
        let expected = service.scores(query);
        assert_eq!(expected.0, "used");
        assert_eq!(expected.1.len(), super::super::catalog().len());
        let worker = service.worker.lock().unwrap();
        // Cold work remains bounded even while hot requests bypass the worker.
        assert_eq!(
            service.scores("uncached query while worker occupied").0,
            "busy"
        );
        let barrier = Barrier::new(13);
        let (sender, receiver) = mpsc::channel();
        std::thread::scope(|scope| {
            for _ in 0..12 {
                let sender = sender.clone();
                let service = &service;
                let barrier = &barrier;
                scope.spawn(move || {
                    barrier.wait();
                    sender.send(service.scores(query)).unwrap();
                });
            }
            barrier.wait();
            let mut completed = Vec::new();
            for _ in 0..12 {
                match receiver.recv_timeout(Duration::from_secs(5)) {
                    Ok(result) => completed.push(result),
                    Err(_) => break,
                }
            }
            // Release before assertions so a regression to blocking worker access
            // fails cleanly instead of stranding the scoped threads.
            drop(worker);
            assert_eq!(
                completed.len(),
                12,
                "hot requests must finish while encoder worker remains locked"
            );
            for actual in completed {
                assert_eq!(actual, expected);
            }
        });
    }
    #[test]
    fn rejects_corrupt_and_mismatched_assets() {
        let manifest = include_str!("../../assets/search/manifest.json");
        let bytes = include_bytes!("../../assets/search/catalog-vectors.bin");
        validate_vectors(manifest, bytes).expect("committed assets must validate");
        assert!(validate_vectors("invalid", bytes).is_err());
        assert!(validate_vectors(manifest, &bytes[..bytes.len() - 1]).is_err());
        let mut changed = bytes.to_vec();
        changed[0] ^= 1;
        assert!(validate_vectors(manifest, &changed).is_err());
        let mut m: serde_json::Value = serde_json::from_str(manifest).unwrap();
        m["engine_revision"] = "other-engine".into();
        assert!(validate_vectors(&m.to_string(), bytes).is_err());
        m = serde_json::from_str(manifest).unwrap();
        changed[..4].copy_from_slice(&f32::NAN.to_le_bytes());
        m["vectors_sha256"] = hash(&changed).into();
        assert!(validate_vectors(&m.to_string(), &changed).is_err());
    }
}
