const paths={calendar:'M8 2v4m8-4v4M3 10h18M5 4h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2m3 12 3 3 5-5',layers:'m12 3 10 5-10 5L2 8l10-5M2 12l10 5 10-5M2 16l10 5 10-5',plus:'M12 5v14M5 12h14',x:'m6 6 12 12M6 18 18 6',search:'M21 21l-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',check:'m5 12 4 4L19 6',info:'M12 11v6m0-10v.01M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',play:'m8 5 11 7-11 7V5',pause:'M8 5v14M16 5v14'};
const icon=name=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.calendar}"/></svg>`;
document.querySelectorAll('[data-icon]').forEach(el=>el.outerHTML=icon(el.dataset.icon));
const $=id=>document.getElementById(id);const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sites=[{id:1,name:'春日站',domain:'spring.example',ready:true},{id:2,name:'海棠',domain:'haitang.example',ready:true},{id:3,name:'北斗',domain:'beidou.example',ready:true},{id:4,name:'拾光',domain:'shiguang.example',ready:true},{id:5,name:'青禾',domain:'qinghe.example',ready:true},{id:6,name:'星河',domain:'xinghe.example',ready:true},{id:7,name:'南风',domain:'nanfeng.example',reason:'缺少 Cookie'},{id:8,name:'远山',domain:'yuanshan.example',reason:'尚未适配'}];
let tasks=[{id:1,site:1,name:'春日站',interval:8,enabled:true,result:'签到成功',time:'今天 08:00'},{id:2,site:2,name:'海棠',interval:8,enabled:true,result:'今日已签到',time:'今天 08:00'},{id:3,site:3,name:'北斗',interval:12,enabled:false,result:'签到成功',time:'昨天 12:00'}];
let records=tasks.map(t=>({...t})),selected=new Set(),mode='batch',view='tasks',busy=false,opener=null;
function eligible(s){return s.ready&&!tasks.some(t=>t.site===s.id)}
function visibleSites(){return sites.filter(s=>s.name.toLowerCase().includes($('siteSearch').value.trim().toLowerCase())).sort((a,b)=>Number(eligible(b))-Number(eligible(a)))}
function renderSites(){const available=sites.filter(eligible);$('eligibleCount').textContent=`${available.length} 个可创建`;$('siteList').innerHTML=visibleSites().map(s=>{const allowed=eligible(s),reason=tasks.some(t=>t.site===s.id)?'已有任务':s.reason;return `<label class="site-row ${allowed?'':'unavailable'}"><input type="${mode==='batch'?'checkbox':'radio'}" name="site" value="${s.id}" ${allowed?'':'disabled'} ${selected.has(s.id)?'checked':''} aria-label="${s.name}${allowed?'':'，'+reason}"><span class="site-initial">${s.name[0]}</span><span class="site-info"><strong>${s.name}</strong><small>${s.domain}</small></span><span class="site-state">${allowed?'已适配':reason}</span></label>`}).join('')||'<p class="no-sites">没有找到站点，请换个名称试试。</p>';syncSelection()}
function syncSelection(){const n=selected.size,available=visibleSites().filter(eligible);$('selectedCount').textContent=`已选 ${n} 个`;$('selectAll').checked=available.length>0&&available.every(s=>selected.has(s.id));$('selectAll').indeterminate=available.some(s=>selected.has(s.id))&&!$('selectAll').checked;$('selectAll').disabled=!available.length;$('createBtn').disabled=!n||busy;$('createBtn').textContent=busy?'正在创建…':n?`创建 ${n} 个签到任务`:'创建签到任务';$('selectionSummary').textContent=n?`已选 ${n} 个站点，将分别创建独立任务`:'请选择需要签到的站点';$('summaryText').textContent=n?`创建 ${n} 个任务，每 ${$('interval').value} 小时尝试签到一次。`:'选择站点后，这里会显示创建内容。'}
function openEditor(next,button){mode=next;opener=button;selected.clear();$('editor').hidden=false;$('feedback').hidden=true;$('siteSearch').value='';$('interval').value='8';$('taskName').value='';$('editorTitle').textContent=mode==='batch'?'批量创建签到任务':'新增签到任务';$('editorDescription').textContent=mode==='batch'?'一次选择多个站点，每个站点分别创建一个任务。':'选择一个站点，签到方式会自动匹配。';$('nameField').hidden=mode==='batch';$('selectAll').parentElement.hidden=mode!=='batch';renderSites();$('editor').scrollIntoView({behavior:'instant',block:'start'});$('siteSearch').focus({preventScroll:true})}
function closeEditor(){if(busy)return;$('editor').hidden=true;opener?.focus({preventScroll:true})}
$('batchBtn').onclick=()=>openEditor('batch',$('batchBtn'));$('addBtn').onclick=()=>openEditor('single',$('addBtn'));$('closeEditor').onclick=$('cancelBtn').onclick=closeEditor;
$('siteSearch').oninput=renderSites;$('interval').onchange=syncSelection;
$('siteList').onchange=e=>{if(!e.target.matches('input'))return;const id=Number(e.target.value);if(mode==='single'){selected.clear();selected.add(id);$('taskName').value=sites.find(s=>s.id===id).name}else{e.target.checked?selected.add(id):selected.delete(id)}renderSites();$('siteList').querySelector(`input[value="${id}"]`)?.focus({preventScroll:true})};
$('selectAll').onchange=e=>{visibleSites().filter(eligible).forEach(s=>e.target.checked?selected.add(s.id):selected.delete(s.id));renderSites()};
$('createBtn').onclick=async()=>{if(!selected.size||busy)return;if(mode==='single'&&!$('taskName').value.trim()){$('taskName').setCustomValidity('请填写任务名称');$('taskName').reportValidity();return}const chosen=[...selected].filter(id=>eligible(sites.find(s=>s.id===id))),interval=Number($('interval').value),name=$('taskName').value.trim();busy=true;syncSelection();$('editor').querySelectorAll('input,select,button').forEach(el=>el.disabled=true);await new Promise(r=>setTimeout(r,650));for(const id of chosen){tasks.push({id:Math.max(...tasks.map(t=>t.id),0)+1,site:id,name:mode==='single'?name:sites.find(s=>s.id===id).name,interval,enabled:true,result:'等待首次执行',time:'尚未执行'})}busy=false;$('editor').querySelectorAll('input,select,button').forEach(el=>el.disabled=false);closeEditor();setView('tasks');$('taskSearch').value='';renderTasks();$('feedback').textContent=`已创建 ${chosen.length} 个签到任务，均已启用。每 ${interval} 小时自动执行，也可点击“立即执行”体验签到。`;$('feedback').hidden=false;$('feedback').scrollIntoView({behavior:'instant',block:'nearest'})};
$('taskName').oninput=()=> $('taskName').setCustomValidity('');
function setView(next){view=next;['tasks','records'].forEach(v=>{$(v+'Tab').classList.toggle('active',v===view);$(v+'Tab').setAttribute('aria-pressed',String(v===view))});$('listTitle').textContent=view==='tasks'?'我的签到任务':'执行记录';$('listDescription').textContent=view==='tasks'?'任务会按设定间隔自动执行。':'查看每次执行的时间和签到结果。';renderTasks()}
$('tasksTab').onclick=()=>setView('tasks');$('recordsTab').onclick=()=>setView('records');$('taskSearch').oninput=renderTasks;$('clearSearch').onclick=()=>{$('taskSearch').value='';renderTasks()};
function renderTasks(){const rows=(view==='tasks'?tasks:records).filter(t=>(t.name+sites.find(s=>s.id===t.site).name).toLowerCase().includes($('taskSearch').value.trim().toLowerCase()));$('taskCount').textContent=tasks.length;$('tableHead').innerHTML=view==='tasks'?'<tr><th>任务 / 站点</th><th>执行间隔</th><th>任务状态</th><th>最近结果</th><th>操作</th></tr>':'<tr><th>任务 / 站点</th><th>执行时间</th><th>签到结果</th><th>说明</th></tr>';$('taskRows').innerHTML=rows.map(t=>{const site=sites.find(s=>s.id===t.site);return `<tr><td><strong>${escapeHTML(t.name)}</strong><small>${site.domain}</small></td>${view==='tasks'?`<td>每 ${t.interval} 小时</td><td><span class="badge ${t.enabled?'':'paused'}">${t.enabled?'已启用':'已暂停'}</span></td><td>${t.result}<small>${t.time}</small></td><td><div class="row-actions"><button class="row-action" data-run="${t.id}" ${t.running?'disabled':''}>${icon('play')}${t.running?'执行中…':'立即执行'}</button><button class="row-action" data-toggle="${t.id}" aria-label="${t.enabled?'暂停':'启用'}${escapeHTML(t.name)}">${icon(t.enabled?'pause':'play')}${t.enabled?'暂停':'启用'}</button></div></td>`:`<td>${t.time}</td><td><span class="badge">${t.result}</span></td><td>模拟执行结果</td>`}</tr>`}).join('');$('empty').hidden=rows.length>0;$('listCount').textContent=`共 ${rows.length} ${view==='tasks'?'个任务':'条记录'}`}
$('taskRows').onclick=async e=>{const toggle=e.target.closest('[data-toggle]'),run=e.target.closest('[data-run]');if(toggle){const t=tasks.find(t=>t.id===Number(toggle.dataset.toggle));t.enabled=!t.enabled;renderTasks();$('taskRows').querySelector(`[data-toggle="${t.id}"]`)?.focus({preventScroll:true})}if(run){const t=tasks.find(t=>t.id===Number(run.dataset.run));if(t.running)return;t.running=true;renderTasks();await new Promise(r=>setTimeout(r,800));t.running=false;t.result='签到成功';t.time='刚刚';records.unshift({...t});renderTasks();$('feedback').textContent=`${t.name}：模拟签到成功。可在执行记录中查看。`;$('feedback').hidden=false}};
renderTasks();if(location.hash==='#batch')openEditor('batch',$('batchBtn'));
